In [106]:
import numpy as np
import matplotlib
matplotlib.use('TkAgg')

import matplotlib.pyplot as plt
%matplotlib inline

import lsst.sims.maf.metrics as metrics
import lsst.sims.maf.slicers as slicers
import lsst.sims.maf.metricBundles as metricBundles
import lsst.sims.maf.db as db
import lsst.sims.maf.utils as utils
import lsst.sims.maf.plots as plots

# open database use OpsimDatabase
#opsdb = db.OpsimDatabase('baseline2018a.db')

# output
#outDir = 'outdir'
#resultsDb = db.ResultsDb(outDir=outDir)

/home/docmaf/stack/python/miniconda3-4.5.4/envs/lsst-scipipe-10a4fa6/lib/python3.6/site-packages/matplotlib/__init__.py:1405: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

  warnings.warn(_use_error_msg)


Introduction Notebook.ipynb*  Untitled.ipynb*  baseline2018a.db*  outdir/


In [4]:
-1//2

-1

In [1]:
count = 0
while count < 5:
   print (count, " 小于 5")
   count = count + 1
else:
   print (count, " 大于或等于 5")

0  小于 5
1  小于 5
2  小于 5
3  小于 5
4  小于 5
5  大于或等于 5


In [14]:
list(range(2,1))

[]

In [11]:
for i in range(-3):
    print (i)
else:
    print ('aha!')

aha!


In [107]:
np.arange(-3)

array([], dtype=int64)

In [108]:
np.arange(0,-3,-1)

array([ 0, -1, -2])

In [17]:
if 1:
    print('hello')

hello


In [18]:
 
for letter in 'Runoob': 
   if letter == 'o':
      pass
      print ('执行 pass 块')
   print ('当前字母 :', letter)
 
print ("Good bye!")

当前字母 : R
当前字母 : u
当前字母 : n
执行 pass 块
当前字母 : o
执行 pass 块
当前字母 : o
当前字母 : b
Good bye!


In [19]:
 
for letter in 'Runoob': 
   if letter == 'o':
 
      print ('执行 pass 块')
   print ('当前字母 :', letter)
 
print ("Good bye!")

当前字母 : R
当前字母 : u
当前字母 : n
执行 pass 块
当前字母 : o
执行 pass 块
当前字母 : o
当前字母 : b
Good bye!


In [23]:
for i in [1, 0]:
    print(i)

1
0


In [21]:
for i in [1, 0]:
    print(i)

builtin_function_or_method

In [3]:
a = [24, 16, 54]
b = []
if   a[0]< a[2] :
    b.append(a[0])
    if  a[1]  <  a[2]:
        b.append(a[1])
        b.append(a[2])
    else:                 
        b.append(a[2])
        b.append(a[1])
        
print(b)

[24, 16, 54]


In [4]:
keyword

NameError: name 'keyword' is not defined

In [8]:
def F(x):
    y=x**(x/3)
    return y

F(6)

36.0

In [17]:
x=np.array([2,3,4,5])

In [20]:
y=np.array([2,3,4,5+1j])

In [21]:
type(y[1])

numpy.complex128

In [27]:
type(range(5))

range

In [28]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [30]:
a = np .arange(0, 20, 1) #＃1维
b = a.reshape((4, 5))   #＃4行5列
c = a.reshape((20, 1))  #＃2维
d = a.reshape((-1, 4))  #＃-1：自动确定

In [31]:
d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [32]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [35]:
a = np.array([1,2,3,4,5])
b = a.copy ()

c1 =  np.dot(np.transpose(a), b)
print(c1)
c2  = np.dot(a, np.transpose(b))
print(c2)

ax  =  np.reshape(a, (5,1))
bx  =  np.reshape(b, (1,5))
c = np.dot(ax, bx)
print(c)

55
55
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [44]:
a=np.arange(12);a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [51]:
b=a[1:4].copy();b

array([100,   2,   3])

In [52]:
b[0]=10;b

array([10,  2,  3])

In [53]:
a

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [42]:
type(a[1][2])

numpy.int64

In [79]:
file = open('New Text Document (2).txt','r')

In [80]:
file = open('newfile.txt', 'a')

In [81]:
file.write('I am created for the course. \n')
file.write('How about you? ')
file.write('How is your exam?')
file.close()

In [2]:
import sympy as sy

x  = sy.Symbol('x')
y  = sy.Symbol('y')

# 给定[-1,1]  (give [-1, 1])
print(sy.solve (x**2 - 1))

ModuleNotFoundError: No module named 'sympy'

In [147]:
dict = {'Name': 'Runoob', 'Age': 7, 'Class': 'First'}
 
print ("dict['Name']: ", dict['Name'])
print ("dict['Age']: ", dict['Age'])

dict['Name']:  Runoob
dict['Age']:  7


In [2]:
dict = {'Name': 'Runoob', 'Age': 7, 'Class': 'First'}
 
print ("dict['Alice']: ", dict['Alice'])

KeyError: 'Alice'

In [148]:
dict['Name']='asdf'
dict

{'Name': 'asdf', 'Age': 7, 'Class': 'First'}

In [4]:
import numpy as np
import numpy.ma as ma
x = np.array([1,2,3,5,7,4,3,2,8,0])
mask = x < 5
mx = ma.array(x,mask=mask)
print(mask)
print(mx)
print(mx.filled())

[ True  True  True False False  True  True  True False  True]
[-- -- -- 5 7 -- -- -- 8 --]
[999999 999999 999999      5      7 999999 999999 999999      8 999999]


In [15]:
class Person(object):
    class_name = "人类"
    
    def __init__(self, name, birth):
        self.name = name
        self.birth = birth
        self.height = 170
        self.legs = 2
        
    def say(self):
        print("我的姓名：", self.name)
        print("我出生于：", self.birth)
        
    def jiafa(self, x, y):
        return x+y

In [17]:
Zhangsan = Person('张三', '1900')

In [8]:
print(Person.class_name)

人类


In [20]:
Zhangsan.height

170

In [26]:
Zhangsan.say()

我的姓名： 张三
我出生于： 1900


In [240]:
class Circle(object):
    Pi = 3.14159265
    
    def __init__(self, radius):
        self.radius = radius
        self.Circ = 2*self.Pi*radius
        
    def Perimeter(self, duplicate=1):
        return 2*self.Pi*radius*duplicate

In [241]:
Circle1 = Circle(1)

In [242]:
Circle1.Perimeter()

NameError: name 'radius' is not defined

In [58]:
Circle.Circ

AttributeError: type object 'Circle' has no attribute 'Circ'

In [74]:
Circle1.Perimeter(4)

25.1327412

In [70]:
Circle1.radius

3

In [78]:
Circle1.Perimeter

<bound method Circle.Perimeter of <__main__.Circle object at 0x7f5d9057c978>>

In [80]:
Circle1.asdf = 1

In [81]:
Circle1.asdf

1

In [98]:
a = 'asdf'

In [99]:
a

'asdf'

In [100]:
a[0]

'a'

In [101]:
a[0]='b'

TypeError: 'str' object does not support item assignment

In [102]:
a(0)='b'

SyntaxError: can't assign to function call (<ipython-input-102-0b12b5585d3a>, line 1)

In [109]:
a.replace('a','b')

'bsdf'

In [114]:
#!/usr/bin/python3
 
#可写函数说明
def printme( str ):
   "打印任何传入的字符串"
   print (str)
   return
 
#调用printme函数
printme( str = "菜鸟教程")

菜鸟教程


In [116]:
#!/usr/bin/python3
 
#可写函数说明
def printinfo( name, age = 35 ):
   "打印任何传入的字符串"
   print ("名字: ", name)
   print ("年龄: ", age)
   return
 
#调用printinfo函数
printinfo( age=50, name="runoob" )
print ("------------------------")
printinfo( name="runoob" )

名字:  runoob
年龄:  50
------------------------
名字:  runoob
年龄:  35


In [120]:
printinfo(age='asd', name = 23)

名字:  23
年龄:  asd


In [121]:
def printinfo( name='asd', age ):
   "打印任何传入的字符串"
   print ("名字: ", name)
   print ("年龄: ", age)
   return

SyntaxError: non-default argument follows default argument (<ipython-input-121-d3576ec7e8b0>, line 1)

In [128]:
def greet_me(**kwargs):
    for key, value in kwargs.items():
        print("{0} = {1}".format(key, value))

greet_me(name="asdf", age = 3, height = 120)

name = asdf
age = 3
height = 120


In [131]:
def test_args_kwargs(arg1, arg2, arg3):
    print("arg1:", arg1)
    print("arg2:", arg2)
    print("arg3:", arg3)
    
kwargs = {"arg3": 3, "arg2": "two", "arg1": 5}
test_args_kwargs(**kwargs)

arg1: 5
arg2: two
arg3: 3


In [134]:
test_args_kwargs(arg1=1, arg2=3,arg3=5)

arg1: 1
arg2: 3
arg3: 5


In [136]:
metricBundles.MetricBundle.plot?

In [138]:
student = {'Tom', 'Jim', 'Mary', 'Tom', 'Jack', 'Rose'}
student

{'Jack', 'Jim', 'Mary', 'Rose', 'Tom'}

In [139]:
list(student)

['Rose', 'Jack', 'Jim', 'Mary', 'Tom']

In [141]:
['Tom', 'Jim', 'Mary', 'Tom', 'Jack', 'Rose']

['Tom', 'Jim', 'Mary', 'Tom', 'Jack', 'Rose']

In [143]:
set(['Tom', 'Jim', 'Mary', 'Tom', 'Jack', 'Rose'])

{'Jack', 'Jim', 'Mary', 'Rose', 'Tom'}

In [152]:
class asdf(object):
    def __init__(self):
        class_name = 'test'
        
    
    def Input(self, str):
        self.Dict['input']  = str     

In [153]:
Test = asdf()

In [154]:
Test.Input('input str')

AttributeError: 'asdf' object has no attribute 'Dict'

In [155]:
a = np.arange(10)

In [156]:
type(a)

numpy.ndarray

In [162]:
np.where(a<5,1,0)

array([1, 1, 1, 1, 1, 0, 0, 0, 0, 0])

In [163]:
np.where(a<5)

(array([0, 1, 2, 3, 4]),)

In [183]:
np.where(a<5)[0]

array([0, 1, 2, 3, 4])

In [164]:
np.asarray(a<5).nonzero()

(array([0, 1, 2, 3, 4]),)

In [166]:
a<5

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [171]:
np.asarray(a<5)

array([ True,  True,  True,  True,  True, False, False, False, False, False], dtype=bool)

In [172]:
np.nonzero([1,3, 4,0, 3])

(array([0, 1, 2, 4]),)

In [182]:
np.nonzero(np.array([1,3, 4,0, 3])<4)

(array([0, 1, 3, 4]),)

In [254]:
np.nonzero(np.array([1,3, 4,0, 3])<4)[0]

array([0, 1, 3, 4])

In [253]:
np.array([1,3, 4,0, 3])<4

array([ True,  True, False,  True,  True], dtype=bool)

In [256]:
index = np.nonzero(np.array([1,3, 4,0, 3])<4)[0]

In [257]:
index[1] = np.nonzero(np.array([1,3, 4,0, 3])<4)[0]

ValueError: setting an array element with a sequence.

In [262]:
index = np.array([0, 1, 3, 4])

In [265]:
np.array(index, np.array([0, 1, 3, 4]))


TypeError: data type not understood

In [269]:
common = np.intersect1d(np.array([1,2,3]), np.array([2,3,4]))

In [270]:
len(common)

2

In [184]:
col = ['observationStartMJD','asdf']

In [187]:
colArr=np.array(col,copy=False, ndmin=1)

In [232]:
class Employee:
   '所有员工的基类'
   empCount = 0
 
   def __init__(self, name, salary):
        self.name = name
        self.salary = salary
        self.empCount += 1
   
   def displayCount(self):
        print("Total Employee %d" %(Employee.empCount)) 
 
   def displayEmployee(self):
        print("Name : ", self.name,  ", Salary: ", self.salary)

In [233]:
Lily = Employee('Lily', 500)

In [234]:
Lily.displayCount()

Total Employee 0


In [231]:
print("Total Employee %d" %(Employee.empCount)) 

Total Employee 0


In [220]:
Employee.empCount

0

In [213]:
Lily = Employee('Lily', 500)

In [251]:
1!=1

False